import type { Distribution } from '@/types';

export const mockDistributions: Distribution[] = [
  {
    id: 'dst-001',
    region: 'West Nile',
    date: '2025-06-15',
    status: 'Planned',
    beneficiaries: 1200,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf-001', name: 'Jane Doe' },
      { id: 'bnf-002', name: 'John Smith' },
      { id: 'bnf-003', name: 'Maria Garcia' },
      { id: 'bnf-004', name: 'Ahmed Hassan' },
      { id: 'bnf-005', name: 'Chen Wei' },
    ],
  },
  {
    id: 'dst-002',
    region: 'Eastern Province',
    date: '2025-06-10',
    status: 'Completed',
    beneficiaries: 850,
    aidType: 'Medical',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf-006', name: 'Sarah Johnson' },
      { id: 'bnf-007', name: 'Carlos Rodriguez' },
      { id: 'bnf-008', name: 'Fatima Al-Rashid' },
    ],
  },
  {
    id: 'dst-003',
    region: 'West Nile',
    date: '2025-05-20',
    status: 'In Progress',
    beneficiaries: 400,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf-009', name: 'Michael Brown' },
      { id: 'bnf-010', name: 'Aisha Mohammed' },
    ],
  },
  {
    id: 'dst-004',
    region: 'Northern Region',
    date: '2025-05-15',
    status: 'Completed',
    beneficiaries: 1000,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf-011', name: 'David Wilson' },
      { id: 'bnf-012', name: 'Yuki Tanaka' },
      { id: 'bnf-013', name: 'Emmanuel Okafor' },
    ],
  },
  {
    id: 'dst-005',
    region: 'Southern District',
    date: '2025-05-05',
    status: 'Completed',
    beneficiaries: 650,
    aidType: 'Shelter',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf-014', name: 'Isabella Martinez' },
      { id: 'bnf-015', name: 'Kwame Mensah' },
    ],
  },
  {
    id: 'dst-006',
    region: 'Central Region',
    date: '2025-04-28',
    status: 'Completed',
    beneficiaries: 780,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Money',
    beneficiaryList: [
      { id: 'bnf-016', name: 'Sophie Dubois' },
      { id: 'bnf-017', name: 'Rajesh Kumar' },
    ],
  },
  {
    id: 'dst-007',
    region: 'Eastern Province',
    date: '2025-04-15',
    status: 'Planned',
    beneficiaries: 920,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf-018', name: 'Anna Kowalski' },
      { id: 'bnf-019', name: 'Omar Farooq' },
    ],
  },
  {
    id: 'dst-008',
    region: 'Northern Region',
    date: '2025-04-10',
    status: 'In Progress',
    beneficiaries: 560,
    aidType: 'Education',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf-020', name: 'Elena Popov' },
      { id: 'bnf-021', name: 'Joseph Kamau' },
    ],
  },
  {
    id: 'dst-009',
    region: 'West Nile',
    date: '2025-03-25',
    status: 'Completed',
    beneficiaries: 1100,
    aidType: 'Food',
    deliveryChannel: 'Cash Transfer',
    beneficiaryList: [
      { id: 'bnf-022', name: 'Lucia Fernandez' },
      { id: 'bnf-023', name: 'Nguyen Van' },
    ],
  },
  {
    id: 'dst-010',
    region: 'Southern District',
    date: '2025-03-18',
    status: 'Completed',
    beneficiaries: 480,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf-024', name: 'Ibrahim Diallo' },
      { id: 'bnf-025', name: 'Nina Andersson' },
    ],
  },
  {
    id: 'dst-011',
    region: 'Central Region',
    date: '2025-03-10',
    status: 'Cancelled',
    beneficiaries: 0,
    aidType: 'Other',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [],
  },
  {
    id: 'dst-012',
    region: 'Eastern Province',
    date: '2025-02-28',
    status: 'Completed',
    beneficiaries: 890,
    aidType: 'Medical',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf-026', name: 'Kenji Yamamoto' },
      { id: 'bnf-027', name: 'Amara Nwosu' },
    ],
  },
];

export const getUniqueRegions = () => {
  return [...new Set(mockDistributions.map(d => d.region))].sort();
};
